### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Michael-J-Ward**
A collection of fixes that I found as I read through the book. Almost all of them are obvious corrections that must have resulted from refactoring the code after the first draft.

The one non-obvious one is the change from `struct Event` to `struct Task`. Chapter `8_0` included both structs and descriptions of both. I *think* my edit is correct, but I am not 100%.

### CODE REVIEW

**Comment by cfsamson** [comment]
I'm super grateful for these fixes! Yes, there has been some refactoring, especially as I worked on the "kqueue, epoll and IOCP" book which creates the event queue which this book relies on.

I'll go through these fixes as soon as I have some time.

**Comment by cfsamson** [comment]
I just have to thank you once again for putting in this work. Good fixes and cought a lot of things I've missed as I changed the API when working through the Epoll book. Greatly appreciated.

And sorry for delaying so long with merging these. It has just been an unfortunate timing of events lately.

**Comment by Michael-J-Ward** [comment]
@cfsamson no, thank YOU for creating such a great resource.

Currently going through [Practical Networked Applications in Rust](https://github.com/pingcap/talent-plan/tree/master/rust) and then I'll swing back for the last two in your series.

Hope you're doing well and staying safe!

**Comment by cfsamson** [comment]
Thanks and you too. I've heard a lot of great things about the Networked Applications series and it's on my todo-list as well.

Take care!

**Pull request merged**
